---
- name: install devel packages
  with_items: "{{ devel_packages }}"
  pkgng:
    name: "{{ item.name }}"
    state: present

- name: install global node packages
  with_items: "{{ node_packages }}"
  become: yes
  become_user: devel
  yarn:
    global: yes
    name: "{{ item.name }}"
    version: "{{ item.version }}"
